# Generated by Django 6.0.1 on 2026-02-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField()),
            ],
        ),
    ]
