# Generated by Django 6.0.1 on 2026-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cognitive_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
