# Generated by Django 6.0.1 on 2026-04-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0003_task_cognitive_load_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtasks',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='cognitive_load',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='isRecurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='recurringDay',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
