# Generated by Django 6.0.1 on 2026-04-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0004_subtasks_remove_task_cognitive_load_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
