# Generated by Django 6.0.1 on 2026-04-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0005_remove_task_task_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='isRecurring',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurringDay',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
